### ISSUE TITLE
Importing neurons, without any annotations or names, not working

### ISSUE THREAD

**Issue by sc0ttwils0n** [schlegelp/CATMAID-to-Blender#20]
I'm looking to import all non-zero length skeletons from Seymour, on MacOS. I figured I'd be able to do so by just specify minimum length as 1, and leaving everything else blank. trying that gives the following:

Python: Traceback (most recent call last):
  File "/Users/swilson/Library/Application Support/Blender/3.6/scripts/addons/CATMAIDImport.py", line 421, in execute
    neuron_names = client.get_names(skeletons_to_retrieve)
  File "/Users/swilson/Library/Application Support/Blender/3.6/scripts/addons/CATMAIDImport.py", line 1713, in get_names
    return self.fetch(url, post=post)
  File "/Users/swilson/Library/Application Support/Blender/3.6/scripts/addons/CATMAIDImport.py", line 1526, in fetch
    raise HTTPError('{} errors encountered: {}'.format(len(errors),
requests.exceptions.HTTPError: 1 errors encountered: 500 Server Error: 'NoneType' object is not iterable for url: https://neurophyla.mrc-lmb.cam.ac.uk/catmaid/drosophila/l1/seymour/1/skeleton/neuronnames

Note that this same error appears regardless of the minimum size threshold or any downsampling values tested. Importing neurons via annotations or names is no problem - is it the case that you cannot leave both of these empty?

**Comment by schlegelp** [comment]
Hi Scott. The "minimum node count" was originally a filter applied _after_ finding neurons search for e.g. a given annotation - i.e. it wasn't intended to be used to load all neurons above a given size. The error message should have been more helpful though.

That said: I just pushed a small update to Github that makes it so that it loads all skeletons above a given node count if:
- all other filter criteria (skeleton IDs, annotations, names) are empty
- Minimim node count is >= 1
